### ISSUE TITLE
Directory data is out-of-date

### ISSUE THREAD

**Issue by g00g1** [PrivateBin/Directory#31]
There are a few thing I can confirm as stalled:

1. **Mozilla Observatory score**. For https://encryp.ch/note, Mozilla Observatory [latest report](https://observatory.mozilla.org/analyze/encryp.ch) shows an "A+" score (as of March 10, 2023), but at the directory home page the "D" score is shown.
2. **GeoIP**. The domain is resolving to 65.21.140.233 / 2a01:4f9:3b:2a5f:7ddb:ea01:41c4:f00b, both are known by DB-IP as ones located in Finland.

This seems like a bug, as previously this data certainly was updated.

**Comment by elrido** [comment]
Hi there,

I went looking into the issue, yesterday. For the GeoIP, we're using the [Creative Commons licensed Free IP country database](https://db-ip.com/db/lite.php). The last update was in January, but even with the latest update it resolves both of these IPs as being in Germany, probably because the holder is a German company (Hetzner)?

After confirming that the score did also report as A+ on the API-URL and that the latest daily cron jobs had reported other sites to have had their score updated in the last days, just not this one, I restarted the service (it had been running for 2 months) and triggered another full update. That score on this one site was the only change that it detected, but at least it is now updated.

I wonder if the API request got cached somewhere, that a service restart was necessary? I'm not aware that the hyper client library caches requests, so there may be a bug in there in how it gets used, that leads to stale results being returned. In any case - for now I'll keep an eye on any differences that crop up right after restarting the service.
